class ContactInfo {
  final String contactPerson;
  final String phone;

  ContactInfo({required this.contactPerson, required this.phone});
}

class Visit {
  final String id;
  final String visitNumber;
  final String visitType;
  final String establishmentClassification;
  final String visitStatus;
  final String establishmentName;
  final String sector;
  final String recordNumber;
  final String distinguishingNumber;
  final String responsiblePerson;
  final String responsiblePersonPhone;
  final String inspectionDepartment;
  final String branch;
  final String region;
  final String city;
  final String district;
  final String street;
  final String creator;
  final String inspector;
  final String inspectorId;
  final String supervisor;
  final String workflow;
  final String creationDate;
  final String visitDate;
  final bool hasViolations;
  final String location;
  final ContactInfo contactInfo;
  final String lastUpdate;
  final int compliance;
  final int fine;
  final int violations;
  final String notes;
  final String status;

  Visit({
    required this.id,
    required this.visitNumber,
    required this.visitType,
    required this.establishmentClassification,
    required this.visitStatus,
    required this.establishmentName,
    required this.sector,
    required this.recordNumber,
    required this.distinguishingNumber,
    required this.responsiblePerson,
    required this.responsiblePersonPhone,
    required this.inspectionDepartment,
    required this.branch,
    required this.region,
    required this.city,
    required this.district,
    required this.street,
    required this.creator,
    required this.inspector,
    required this.inspectorId,
    required this.supervisor,
    required this.workflow,
    required this.creationDate,
    required this.visitDate,
    required this.hasViolations,
    required this.location,
    required this.contactInfo,
    required this.lastUpdate,
    required this.compliance,
    required this.fine,
    required this.violations,
    required this.notes,
    required this.status,
  });
}



final List<Visit> visits = [
  Visit(
    id: '1',
    visitNumber: 'VS00012345',
    visitType: 'زيارة رقابية ميدانية',
    establishmentClassification: '',
    visitStatus: 'انتهت وجارى إعتمادها',
    establishmentName: 'فندق ميرة السد',
    sector: 'فنادق',
    recordNumber: '',
    distinguishingNumber: '23017',
    responsiblePerson: '',
    responsiblePersonPhone: '',
    inspectionDepartment: 'مرفق الضيافة السياحي',
    branch: 'الفرع الرئيسى',
    region: 'منطقة مكة المكرمة',
    city: 'مكه المكرمه',
    district: '',
    street: '',
    creator: 'أحمد محمد العلي',
    inspector: 'أحمد محمد العلي',
    inspectorId: '',
    supervisor: '',
    workflow: 'سير عمل المخالفات غير الفورية',
    creationDate: '2024-01-15',
    visitDate: '2024-01-15',
    hasViolations: true,
    location: 'منطقة مكة المكرمة، مكه المكرمه',
    contactInfo: ContactInfo(
      contactPerson: 'أحمد محمد العلي',
      phone: '0501234567',
    ),
    lastUpdate: '2024-01-15',
    compliance: 45,
    fine: 2500,
    violations: 3,
    notes: 'تم العثور على مخالفات في النظافة العامة والسلامة',
    status: 'active',
  ),
  Visit(
    id: '2',
    visitNumber: 'VS00012346',
    visitType: 'زيارة رقابية ميدانية',
    establishmentClassification: '',
    visitStatus: 'انتهت وجارى إعتمادها',
    establishmentName: 'فندق مناسك لؤلؤة القصر',
    sector: 'فنادق',
    recordNumber: '',
    distinguishingNumber: '26120',
    responsiblePerson: '',
    responsiblePersonPhone: '',
    inspectionDepartment: 'مرفق الضيافة السياحي',
    branch: 'الفرع الرئيسى',
    region: 'منطقة مكة المكرمة',
    city: 'مكه المكرمه',
    district: '',
    street: '',
    creator: 'محمد عبدالرحمن السعيد',
    inspector: 'محمد عبدالرحمن السعيد',
    inspectorId: '',
    supervisor: '',
    workflow: 'سير عمل المخالفات غير الفورية',
    creationDate: '2024-01-16',
    visitDate: '2024-01-16',
    hasViolations: true,
    location: 'منطقة مكة المكرمة، مكه المكرمه',
    contactInfo: ContactInfo(
      contactPerson: 'محمد عبدالرحمن السعيد',
      phone: '0502345678',
    ),
    lastUpdate: '2024-01-16',
    compliance: 52,
    fine: 1800,
    violations: 2,
    notes: 'مخالفات في شهادات الصحة والسلامة',
    status: 'scheduled',

  ),
  Visit(
    id: '3',
    visitNumber: 'VS00012347',
    visitType: 'زيارة رقابية ميدانية',
    establishmentClassification: 'نجمة واحدة',
    visitStatus: 'انتهت وجارى إعتمادها',
    establishmentName: 'فندق دار اليوسف',
    sector: 'فنادق',
    recordNumber: '4031102351',
    distinguishingNumber: '',
    responsiblePerson: 'خالد أحمد القحطاني',
    responsiblePersonPhone: '0503456789',
    inspectionDepartment: 'مرفق الضيافة السياحي',
    branch: 'الفرع الرئيسى',
    region: 'منطقة مكة المكرمة',
    city: 'مكه المكرمه',
    district: 'المسفلة',
    street: 'ابراهيم الخليل',
    creator: 'عبدالعزيز محمد الغامدي',
    inspector: 'عبدالعزيز محمد الغامدي',
    inspectorId: '1234567890',
    supervisor: '',
    workflow: 'سير عمل الزيارات',
    creationDate: '2024-01-17',
    visitDate: '2024-01-17',
    hasViolations: true,
    location: 'منطقة مكة المكرمة، مكه المكرمه، المسفلة، ابراهيم الخليل',
    contactInfo: ContactInfo(
      contactPerson: 'خالد أحمد القحطاني',
      phone: '0503456789',
    ),
    lastUpdate: '2024-01-17',
    compliance: 38,
    fine: 3200,
    violations: 5,
    notes: 'مخالفات متعددة في النظافة والسلامة المهنية',
    status: 'scheduled',

  ),
  Visit(
    id: '4',
    visitNumber: 'VS00012348',
    visitType: 'زيارة رقابية ميدانية',
    establishmentClassification: 'نجمتان',
    visitStatus: 'انتهت وجارى إعتمادها',
    establishmentName: 'فندق الصفوة البركة',
    sector: 'فنادق',
    recordNumber: '4031109876',
    distinguishingNumber: '27891',
    responsiblePerson: 'سامي عبدالله الحربي',
    responsiblePersonPhone: '0504567890',
    inspectionDepartment: 'مرفق الضيافة السياحي',
    branch: 'الفرع الرئيسى',
    region: 'منطقة مكة المكرمة',
    city: 'مكه المكرمه',
    district: 'العزيزية',
    street: 'شارع الجامعة',
    creator: 'بدر فهد المطيري',
    inspector: 'بدر فهد المطيري',
    inspectorId: '2233445566',
    supervisor: '',
    workflow: 'سير عمل الزيارات',
    creationDate: '2024-01-18',
    visitDate: '2024-01-18',
    hasViolations: false,
    location: 'مكة المكرمة، العزيزية، شارع الجامعة',
    contactInfo: ContactInfo(
      contactPerson: 'سامي عبدالله الحربي',
      phone: '0504567890',
    ),
    lastUpdate: '2024-01-18',
    compliance: 90,
    fine: 0,
    violations: 0,
    notes: 'تمت الزيارة بنجاح دون مخالفات',
    status: 'scheduled',

  ),
  Visit(
    id: '5',
    visitNumber: 'VS00012349',
    visitType: 'زيارة متابعة',
    establishmentClassification: 'ثلاث نجوم',
    visitStatus: 'جارى العمل عليها',
    establishmentName: 'فندق دار الهدى',
    sector: 'فنادق',
    recordNumber: '4031112222',
    distinguishingNumber: '29551',
    responsiblePerson: 'عبدالرحيم ناصر المالكي',
    responsiblePersonPhone: '0505678901',
    inspectionDepartment: 'مرفق الضيافة السياحي',
    branch: 'فرع جدة',
    region: 'منطقة مكة المكرمة',
    city: 'جدة',
    district: 'البلد',
    street: 'شارع الملك عبدالعزيز',
    creator: 'علي خالد الزهراني',
    inspector: 'علي خالد الزهراني',
    inspectorId: '9988776655',
    supervisor: '',
    workflow: 'سير عمل المخالفات الفورية',
    creationDate: '2024-01-19',
    visitDate: '2024-01-19',
    hasViolations: true,
    location: 'جدة، البلد، شارع الملك عبدالعزيز',
    contactInfo: ContactInfo(
      contactPerson: 'عبدالرحيم ناصر المالكي',
      phone: '0505678901',
    ),
    lastUpdate: '2024-01-19',
    compliance: 60,
    fine: 1000,
    violations: 1,
    notes: 'مخالفة بسيطة تتعلق بترخيص النشاط',
    status: 'scheduled',

  ),
  Visit(
    id: '6',
    visitNumber: 'VS00012350',
    visitType: 'زيارة تفتيش دوري',
    establishmentClassification: 'أربع نجوم',
    visitStatus: 'انتهت وجارى إعتمادها',
    establishmentName: 'فندق شذا مكة',
    sector: 'فنادق',
    recordNumber: '4031113333',
    distinguishingNumber: '30511',
    responsiblePerson: 'عبدالاله محمد العتيبي',
    responsiblePersonPhone: '0506789012',
    inspectionDepartment: 'مرفق الضيافة السياحي',
    branch: 'الفرع الرئيسى',
    region: 'منطقة مكة المكرمة',
    city: 'مكه المكرمه',
    district: 'أجياد',
    street: 'شارع أجياد العام',
    creator: 'نايف عبدالله القحطاني',
    inspector: 'نايف عبدالله القحطاني',
    inspectorId: '1122334455',
    supervisor: '',
    workflow: 'سير عمل الزيارات',
    creationDate: '2024-01-20',
    visitDate: '2024-01-20',
    hasViolations: true,
    location: 'مكة المكرمة، أجياد، شارع أجياد العام',
    contactInfo: ContactInfo(
      contactPerson: 'عبدالاله محمد العتيبي',
      phone: '0506789012',
    ),
    lastUpdate: '2024-01-20',
    compliance: 72,
    fine: 2000,
    violations: 2,
    notes: 'وجود بعض المخالفات في إجراءات النظافة العامة',
    status: 'needs_modification',

  ),
  Visit(
    id: '7',
    visitNumber: 'VS00012351',
    visitType: 'زيارة ميدانية خاصة',
    establishmentClassification: '',
    visitStatus: 'انتهت وجارى إعتمادها',
    establishmentName: 'مطعم بيت الشاورما',
    sector: 'مطاعم',
    recordNumber: '',
    distinguishingNumber: '31222',
    responsiblePerson: 'فهد سعود الشمري',
    responsiblePersonPhone: '0507890123',
    inspectionDepartment: 'الرقابة الغذائية',
    branch: 'فرع الطائف',
    region: 'منطقة مكة المكرمة',
    city: 'الطائف',
    district: 'الفيصلية',
    street: 'شارع الستين',
    creator: 'سعد عبدالرحمن الغامدي',
    inspector: 'سعد عبدالرحمن الغامدي',
    inspectorId: '',
    supervisor: '',
    workflow: 'سير عمل الزيارات الدورية',
    creationDate: '2024-01-21',
    visitDate: '2024-01-21',
    hasViolations: true,
    location: 'الطائف، الفيصلية، شارع الستين',
    contactInfo: ContactInfo(
      contactPerson: 'فهد سعود الشمري',
      phone: '0507890123',
    ),
    lastUpdate: '2024-01-21',
    compliance: 55,
    fine: 1500,
    violations: 2,
    notes: 'عدم الالتزام بدرجات الحرارة المناسبة للأطعمة',
    status: 'needs_modification',

  ),
  Visit(
    id: '8',
    visitNumber: 'VS00012352',
    visitType: 'زيارة رقابية ميدانية',
    establishmentClassification: 'خمس نجوم',
    visitStatus: 'انتهت وجارى إعتمادها',
    establishmentName: 'فندق برج الساعة',
    sector: 'فنادق',
    recordNumber: '4031114444',
    distinguishingNumber: '32177',
    responsiblePerson: 'عبدالله ناصر العوفي',
    responsiblePersonPhone: '0508901234',
    inspectionDepartment: 'مرفق الضيافة السياحي',
    branch: 'الفرع الرئيسى',
    region: 'منطقة مكة المكرمة',
    city: 'مكه المكرمه',
    district: 'المسفلة',
    street: 'شارع أجياد',
    creator: 'بسام ماجد الحربي',
    inspector: 'بسام ماجد الحربي',
    inspectorId: '4455667788',
    supervisor: '',
    workflow: 'سير عمل المخالفات غير الفورية',
    creationDate: '2024-01-22',
    visitDate: '2024-01-22',
    hasViolations: false,
    location: 'مكة المكرمة، المسفلة، شارع أجياد',
    contactInfo: ContactInfo(
      contactPerson: 'عبدالله ناصر العوفي',
      phone: '0508901234',
    ),
    lastUpdate: '2024-01-22',
    compliance: 100,
    fine: 0,
    violations: 0,
    notes: 'جميع المعايير مطابقة للأنظمة',
    status: 'needs_modification',

  ),
  Visit(
    id: '9',
    visitNumber: 'VS00012353',
    visitType: 'زيارة متابعة خاصة',
    establishmentClassification: '',
    visitStatus: 'انتهت وجارى إعتمادها',
    establishmentName: 'مطعم الذوق الرفيع',
    sector: 'مطاعم',
    recordNumber: '',
    distinguishingNumber: '33501',
    responsiblePerson: 'راشد عبدالله العمري',
    responsiblePersonPhone: '0509012345',
    inspectionDepartment: 'الرقابة الغذائية',
    branch: 'فرع جدة',
    region: 'منطقة مكة المكرمة',
    city: 'جدة',
    district: 'الرويس',
    street: 'شارع فلسطين',
    creator: 'نواف علي السبيعي',
    inspector: 'نواف علي السبيعي',
    inspectorId: '',
    supervisor: '',
    workflow: 'سير عمل المخالفات الفورية',
    creationDate: '2024-01-23',
    visitDate: '2024-01-23',
    hasViolations: true,
    location: 'جدة، الرويس، شارع فلسطين',
    contactInfo: ContactInfo(
      contactPerson: 'راشد عبدالله العمري',
      phone: '0509012345',
    ),
    lastUpdate: '2024-01-23',
    compliance: 68,
    fine: 1200,
    violations: 1,
    notes: 'تم ضبط لحوم غير صالحة للاستهلاك البشري',
    status: 'finished',
  ),
  Visit(
    id: '10',
    visitNumber: 'VS00012354',
    visitType: 'زيارة تفتيش روتينية',
    establishmentClassification: 'أربع نجوم',
    visitStatus: 'انتهت وجارى إعتمادها',
    establishmentName: 'فندق منى بلازا',
    sector: 'فنادق',
    recordNumber: '4031115555',
    distinguishingNumber: '34177',
    responsiblePerson: 'سعود محمد الغامدي',
    responsiblePersonPhone: '0500123456',
    inspectionDepartment: 'مرفق الضيافة السياحي',
    branch: 'الفرع الرئيسى',
    region: 'منطقة مكة المكرمة',
    city: 'مكه المكرمه',
    district: 'العزيزية',
    street: 'شارع الهجرة',
    creator: 'خالد عبدالكريم الشريف',
    inspector: 'خالد عبدالكريم الشريف',
    inspectorId: '',
    supervisor: '',
    workflow: 'سير عمل الزيارات',
    creationDate: '2024-01-24',
    visitDate: '2024-01-24',
    hasViolations: false,
    location: 'مكة المكرمة، العزيزية، شارع الهجرة',
    contactInfo: ContactInfo(
      contactPerson: 'سعود محمد الغامدي',
      phone: '0500123456',
    ),
    lastUpdate: '2024-01-24',
    compliance: 98,
    fine: 0,
    violations: 0,
    notes: 'الفندق ملتزم بجميع الاشتراطات',
    status: 'finished',

  ),

];

final List<Visit> visitsEn = [
Visit(
id: '1',
visitNumber: 'VS00012345',
visitType: 'Field Inspection Visit',
establishmentClassification: '',
visitStatus: 'Completed and awaiting approval',
establishmentName: 'Mira Al-Sad Hotel',
sector: 'Hotels',
recordNumber: '',
distinguishingNumber: '23017',
responsiblePerson: '',
responsiblePersonPhone: '',
inspectionDepartment: 'Tourism Hospitality Facility',
branch: 'Main Branch',
region: 'Mecca Region',
city: 'Mecca',
district: '',
street: '',
creator: 'Ahmed Mohamed Al-Ali',
inspector: 'Ahmed Mohamed Al-Ali',
inspectorId: '',
supervisor: '',
workflow: 'Non-Immediate Violation Workflow',
creationDate: '2024-01-15',
visitDate: '2024-01-15',
hasViolations: true,
location: 'Mecca Region, Mecca',
contactInfo: ContactInfo(
contactPerson: 'Ahmed Mohamed Al-Ali',
phone: '0501234567',
),
lastUpdate: '2024-01-15',
compliance: 45,
fine: 2500,
violations: 3,
notes: 'Violations found regarding general cleanliness and safety',
  status: 'active',

),
Visit(
id: '2',
visitNumber: 'VS00012346',
visitType: 'Field Inspection Visit',
establishmentClassification: '',
visitStatus: 'Completed and awaiting approval',
establishmentName: 'Manasik Pearl Hotel',
sector: 'Hotels',
recordNumber: '',
distinguishingNumber: '26120',
responsiblePerson: '',
responsiblePersonPhone: '',
inspectionDepartment: 'Tourism Hospitality Facility',
branch: 'Main Branch',
region: 'Mecca Region',
city: 'Mecca',
district: '',
street: '',
creator: 'Mohamed Abdulrahman Al-Saeed',
inspector: 'Mohamed Abdulrahman Al-Saeed',
inspectorId: '',
supervisor: '',
workflow: 'Non-Immediate Violation Workflow',
creationDate: '2024-01-16',
visitDate: '2024-01-16',
hasViolations: true,
location: 'Mecca Region, Mecca',
contactInfo: ContactInfo(
contactPerson: 'Mohamed Abdulrahman Al-Saeed',
phone: '0502345678',
),
lastUpdate: '2024-01-16',
compliance: 52,
fine: 1800,
violations: 2,
notes: 'Violations found regarding health and safety certificates',
  status: 'scheduled',

),
Visit(
id: '3',
visitNumber: 'VS00012347',
visitType: 'Field Inspection Visit',
establishmentClassification: 'One Star',
visitStatus: 'Completed and awaiting approval',
establishmentName: 'Dar Al-Youssef Hotel',
sector: 'Hotels',
recordNumber: '4031102351',
distinguishingNumber: '',
responsiblePerson: 'Khaled Ahmed Al-Qahtani',
responsiblePersonPhone: '0503456789',
inspectionDepartment: 'Tourism Hospitality Facility',
branch: 'Main Branch',
region: 'Mecca Region',
city: 'Mecca',
district: 'Al-Misfalah',
street: 'Ibrahim Al-Khalil',
creator: 'Abdulaziz Mohamed Al-Ghamdi',
inspector: 'Abdulaziz Mohamed Al-Ghamdi',
inspectorId: '1234567890',
supervisor: '',
workflow: 'Visit Workflow',
creationDate: '2024-01-17',
visitDate: '2024-01-17',
hasViolations: true,
location: 'Mecca Region, Mecca, Al-Misfalah, Ibrahim Al-Khalil',
contactInfo: ContactInfo(
contactPerson: 'Khaled Ahmed Al-Qahtani',
phone: '0503456789',
),
lastUpdate: '2024-01-17',
compliance: 38,
fine: 3200,
violations: 5,
notes: 'Multiple violations in cleanliness and safety procedures',
  status: 'scheduled',

),
Visit(
id: '4',
visitNumber: 'VS00012348',
visitType: 'Field Inspection Visit',
establishmentClassification: 'Two Stars',
visitStatus: 'Completed and awaiting approval',
establishmentName: 'Al-Safwa Al-Barakah Hotel',
sector: 'Hotels',
recordNumber: '4031109876',
distinguishingNumber: '27891',
responsiblePerson: 'Sami Abdullah Al-Harbi',
responsiblePersonPhone: '0504567890',
inspectionDepartment: 'Tourism Hospitality Facility',
branch: 'Main Branch',
region: 'Mecca Region',
city: 'Mecca',
district: 'Al-Aziziyah',
street: 'University Street',
creator: 'Badr Fahad Al-Mutairi',
inspector: 'Badr Fahad Al-Mutairi',
inspectorId: '2233445566',
supervisor: '',
workflow: 'Visit Workflow',
creationDate: '2024-01-18',
visitDate: '2024-01-18',
hasViolations: false,
location: 'Mecca, Al-Aziziyah, University Street',
contactInfo: ContactInfo(
contactPerson: 'Sami Abdullah Al-Harbi',
phone: '0504567890',
),
lastUpdate: '2024-01-18',
compliance: 90,
fine: 0,
violations: 0,
notes: 'The visit was successful with no violations',
  status: 'scheduled',

),
Visit(
id: '5',
visitNumber: 'VS00012349',
visitType: 'Follow-up Visit',
establishmentClassification: 'Three Stars',
visitStatus: 'In progress',
establishmentName: 'Dar Al-Huda Hotel',
sector: 'Hotels',
recordNumber: '4031112222',
distinguishingNumber: '29551',
responsiblePerson: 'Abdulrahim Nasser Al-Maliki',
responsiblePersonPhone: '0505678901',
inspectionDepartment: 'Tourism Hospitality Facility',
branch: 'Jeddah Branch',
region: 'Mecca Region',
city: 'Jeddah',
district: 'Al-Balad',
street: 'King Abdulaziz Street',
creator: 'Ali Khalid Al-Zahrani',
inspector: 'Ali Khalid Al-Zahrani',
inspectorId: '9988776655',
supervisor: '',
workflow: 'Immediate Violation Workflow',
creationDate: '2024-01-19',
visitDate: '2024-01-19',
hasViolations: true,
location: 'Jeddah, Al-Balad, King Abdulaziz Street',
contactInfo: ContactInfo(
contactPerson: 'Abdulrahim Nasser Al-Maliki',
phone: '0505678901',
),
lastUpdate: '2024-01-19',
compliance: 60,
fine: 1000,
violations: 1,
notes: 'Minor violation regarding activity licensing',
  status: 'scheduled',

),
Visit(
id: '6',
visitNumber: 'VS00012350',
visitType: 'Routine Inspection Visit',
establishmentClassification: 'Four Stars',
visitStatus: 'Completed and awaiting approval',
establishmentName: 'Shaza Mecca Hotel',
sector: 'Hotels',
recordNumber: '4031113333',
distinguishingNumber: '30511',
responsiblePerson: 'Abdellah Mohamed Al-Otaibi',
responsiblePersonPhone: '0506789012',
inspectionDepartment: 'Tourism Hospitality Facility',
branch: 'Main Branch',
region: 'Mecca Region',
city: 'Mecca',
district: 'Ajyad',
street: 'Ajyad General Street',
creator: 'Naif Abdullah Al-Qahtani',
inspector: 'Naif Abdullah Al-Qahtani',
inspectorId: '1122334455',
supervisor: '',
workflow: 'Visit Workflow',
creationDate: '2024-01-20',
visitDate: '2024-01-20',
hasViolations: true,
location: 'Mecca, Ajyad, Ajyad General Street',
contactInfo: ContactInfo(
contactPerson: 'Abdellah Mohamed Al-Otaibi',
phone: '0506789012',
),
lastUpdate: '2024-01-20',
compliance: 72,
fine: 2000,
violations: 2,
notes: 'Some violations found regarding general cleanliness procedures',
  status: 'needs_modification',

),
Visit(
id: '7',
visitNumber: 'VS00012351',
visitType: 'Special Field Visit',
establishmentClassification: '',
visitStatus: 'Completed and awaiting approval',
establishmentName: 'Shawarma House Restaurant',
sector: 'Restaurants',
recordNumber: '',
distinguishingNumber: '31222',
responsiblePerson: 'Fahd Saud Al-Shammari',
responsiblePersonPhone: '0507890123',
inspectionDepartment: 'Food Control',
branch: 'Taif Branch',
region: 'Mecca Region',
  city: 'Taif',
  district: 'Al-Faisaliah',
  street: 'Sixty Street',
  creator: 'Saad Abdulrahman Al-Ghamdi',
  inspector: 'Saad Abdulrahman Al-Ghamdi',
  inspectorId: '',
  supervisor: '',
  workflow: 'Routine Visit Workflow',
  creationDate: '2024-01-21',
  visitDate: '2024-01-21',
  hasViolations: true,
  location: 'Taif, Al-Faisaliah, Sixty Street',
  contactInfo: ContactInfo(
    contactPerson: 'Fahd Saud Al-Shammari',
    phone: '0507890123',
  ),
  lastUpdate: '2024-01-21',
  compliance: 55,
  fine: 1500,
  violations: 2,
  notes: 'Failure to maintain proper food temperature',
  status: 'needs_modification',

),
  Visit(
    id: '8',
    visitNumber: 'VS00012352',
    visitType: 'Field Inspection Visit',
    establishmentClassification: 'Five Stars',
    visitStatus: 'Completed and awaiting approval',
    establishmentName: 'Abraj Al-Saada Hotel',
    sector: 'Hotels',
    recordNumber: '4031114444',
    distinguishingNumber: '32177',
    responsiblePerson: 'Abdullah Nasser Al-Oufi',
    responsiblePersonPhone: '0508901234',
    inspectionDepartment: 'Tourism Hospitality Facility',
    branch: 'Main Branch',
    region: 'Mecca Region',
    city: 'Mecca',
    district: 'Al-Misfalah',
    street: 'Ajyad Street',
    creator: 'Bassem Majed Al-Harbi',
    inspector: 'Bassem Majed Al-Harbi',
    inspectorId: '4455667788',
    supervisor: '',
    workflow: 'Non-Immediate Violation Workflow',
    creationDate: '2024-01-22',
    visitDate: '2024-01-22',
    hasViolations: false,
    location: 'Mecca, Al-Misfalah, Ajyad Street',
    contactInfo: ContactInfo(
      contactPerson: 'Abdullah Nasser Al-Oufi',
      phone: '0508901234',
    ),
    lastUpdate: '2024-01-22',
    compliance: 100,
    fine: 0,
    violations: 0,
    notes: 'All standards comply with regulations',
    status: 'needs_modification',

  ),
  Visit(
    id: '9',
    visitNumber: 'VS00012353',
    visitType: 'Special Follow-up Visit',
    establishmentClassification: '',
    visitStatus: 'Completed and awaiting approval',
    establishmentName: 'Fine Taste Restaurant',
    sector: 'Restaurants',
    recordNumber: '',
    distinguishingNumber: '33501',
    responsiblePerson: 'Rashid Abdullah Al-Omari',
    responsiblePersonPhone: '0509012345',
    inspectionDepartment: 'Food Control',
    branch: 'Jeddah Branch',
    region: 'Mecca Region',
    city: 'Jeddah',
    district: 'Al-Ruwais',
    street: 'Palestine Street',
    creator: 'Nawaf Ali Al-Subaie',
    inspector: 'Nawaf Ali Al-Subaie',
    inspectorId: '',
    supervisor: '',
    workflow: 'Immediate Violation Workflow',
    creationDate: '2024-01-23',
    visitDate: '2024-01-23',
    hasViolations: true,
    location: 'Jeddah, Al-Ruwais, Palestine Street',
    contactInfo: ContactInfo(
      contactPerson: 'Rashid Abdullah Al-Omari',
      phone: '0509012345',
    ),
    lastUpdate: '2024-01-23',
    compliance: 68,
    fine: 1200,
    violations: 1,
    notes: 'Unfit meat for human consumption was found',
    status: 'finished',
  ),
  Visit(
    id: '10',
    visitNumber: 'VS00012354',
    visitType: 'Routine Inspection Visit',
    establishmentClassification: 'Four Stars',
    visitStatus: 'Completed and awaiting approval',
    establishmentName: 'Mina Plaza Hotel',
    sector: 'Hotels',
    recordNumber: '4031115555',
    distinguishingNumber: '34177',
    responsiblePerson: 'Saud Mohamed Al-Ghamdi',
    responsiblePersonPhone: '0500123456',
    inspectionDepartment: 'Tourism Hospitality Facility',
    branch: 'Main Branch',
    region: 'Mecca Region',
    city: 'Mecca',
    district: 'Al-Aziziyah',
    street: 'Al-Hijrah Street',
    creator: 'Khalid Abdulkarim Al-Sharif',
    inspector: 'Khalid Abdulkarim Al-Sharif',
    inspectorId: '',
    supervisor: '',
    workflow: 'Visit Workflow',
    creationDate: '2024-01-24',
    visitDate: '2024-01-24',
    hasViolations: false,
    location: 'Mecca, Al-Aziziyah, Al-Hijrah Street',
    contactInfo: ContactInfo(
      contactPerson: 'Saud Mohamed Al-Ghamdi',
      phone: '0500123456',
    ),
    lastUpdate: '2024-01-24',
    compliance: 98,
    fine: 0,
    violations: 0,
    notes: 'The hotel complies with all requirements',
    status: 'finished',

  ),
];


